version: "3.8"
services:
    agile:
        tty: true
        image: jupyter/pyspark-notebook:latest
        user: root
        environment:
            GRANT_SUDO: "yes"
        ports:
            - "8888:8888"
        volumes:
            - ./work:/home/jovyan/work
        command: start-notebook.sh --NotebookApp.token=''
