name: jupyter_hub
services:
  jupyter-hub:
    build:
      context: /home/milu/jupyter_hub
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    cpu_shares: 90
    command: []
    container_name: jupyterhub
    deploy:
      resources:
        limits:
          memory: 7943M
    environment:
      - DOCKER_NETWORK_NAME=jupyterhub-network
      - DOCKER_NOTEBOOK_IMAGE=quay.io/jupyter/base-notebook:latest
    hostname: jupyterhub
    image: jupyterhub:latest
    ports:
      - mode: ingress
        target: 8000
        published: "8181"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/milu/jupyter_hub/jupyterhub_config.py
        target: /srv/jupyterhub/jupyterhub_config.py
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /home/milu/jupyter_hub/data
        target: /data
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    networks:
      - jupyterhub-network
    privileged: false
networks:
  jupyterhub-network:
    name: jupyterhub-network
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: ""
  index: /
  is_uncontrolled: false
  port_map: "8181"
  scheme: http
  title:
    custom: jupyterhub
