version: "3.8"
services:
    juptyer:
        tty: true
        image: quay.io/jupyter/base-notebook:latest
        user: root
        environment:
            GRANT_SUDO: "yes"
        ports:
            - "8888:8888"
        volumes:
            - ./work:/home/jovyan/work
        command: start-notebook.sh --NotebookApp.token=''
        networks:
        - jupyter

networks:
  jupyter:
    name: jupyter
